
Vagrant.configure("2") do |config|

  config.omnibus.chef_version = :latest

  config.vm.define "web" do |web|
    web.vm.box = "precise64"
    web.vm.box_url = "http://files.vagrantup.com/precise64.box"
    web.vm.network :private_network, ip: "192.168.100.10"
    web.vm.host_name = "web.local"
 
    web.vm.provision "chef_solo" do |chef|
      chef.add_recipe "nginx"
      chef.add_recipe "mongodb"
      chef.add_recipe "git"
      chef.add_recipe "nodejs"
    end
  end

end
